" 显示行号
set number

" 设置在命令行界面最下面显示当前模式等
set showmode

" 突出显示当前行
set cursorline

" 启动时隐去援助提示
set shortmess=atI

" 自动语法高亮
syntax on

" 不需要备份
set nobackup

" 没有保存或文件只读时弹出确认
set confirm

" 鼠标可用
set mouse=a

" 自动切换当前目录为当前文件所在的目录
set autochdir

" 设定 tab 长度为 4
set tabstop=4
" 设定 << 和 >> 命令移动时的宽度为 4
set shiftwidth=4
" 使得按退格键时可以一次删掉 4 个空格
set softtabstop=4
set expandtab
set smarttab

" 文件自动检测外部更改
set autoread

" 自动对齐
set autoindent

" 智能缩进
set smartindent

" 输入搜索内容时就显示搜索结果
set incsearch

" 高亮查找匹配
set hlsearch

" 搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set ignorecase smartcase

" 关闭错误信息响铃
set noerrorbells

" 关闭使用可视响铃代替呼叫
set novisualbell

" 置空错误铃声的终端代码
set t_vb=

" 背景色
set background=dark

" 显示匹配
set showmatch

" 显示标尺，就是在右下角显示光标位置
set ruler

" 关闭 vi 兼容模式
set nocompatible

" 设置 backspace 的工作方式，解决删除键不能删除的问题
set backspace=indent,eol,start

" 允许折叠
set foldenable

"""""""""""""""""设置折叠"""""""""""""""""""""
" 根据语法折叠
set foldmethod=syntax

" 设置折叠区域的宽度
set foldcolumn=0

" 设置键盘映射，通过空格设置折叠
nnoremap <space> @=((foldclosed(line('.')<0)?'zc':'zo'))<CR>
""""""""""""""""""""""""""""""""""""""""""""""

" 不要闪烁
set novisualbell

" 启动显示状态行
set laststatus=2

" 浅色显示当前行
autocmd InsertLeave * se nocul

" 用浅色高亮当前行
autocmd InsertEnter * se cul

" 显示输入的命令
set showcmd

" 被分割窗口之间显示空白
set fillchars=vert:/
set fillchars=stl:/
set fillchars=stlnc:/

" Python 文件的一般设置，比如不要 tab 等
autocmd FileType python set tabstop=4 shiftwidth=4 expandtab
autocmd FileType python map <F12> :!python %<CR>

" 选中状态下 Ctrl+c 复制
vmap <C-c> "+y

" paste模式快捷键
set pastetoggle=<F11>
