---
- name: Install python3
  yum:
    name: python3
    state: latest

- name: Update pip for root
  shell: |
      pip3 install pip -U
      pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

- name: Create virtualenv for root
  shell: |
      pip install virtualenv
      python3 -m venv env3

- name: Set activate for root
  lineinfile:
    dest: ~/.bashrc
    line: "source ~/env3/bin/activate"
    state: present

- name: Update pip for root
  shell: |
      pip3 install pip -U
      pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

- name: Update env pip for root
  shell: |
      source ~/env3/bin/activate
      pip install pip -U

- name: Update pip for ops
  become: true
  become_user: ops
  become_method: sudo
  shell: |
      pip3 install pip -U
      pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

- name: Create virtualenv for ops
  become: true
  become_user: ops
  become_method: sudo
  shell: |
      cd /home/ops
      pip install virtualenv
      python3 -m venv env3

- name: Set activate for ops
  become: true
  become_user: ops
  become_method: sudo
  lineinfile:
    dest: /home/ops/.bashrc
    line: "source /home/ops/env3/bin/activate"
    state: present

- name: Update env pip for ops
  become: true
  become_user: ops
  become_method: sudo
  shell: |
      cd /home/ops
      source ~/env3/bin/activate
      pip install pip -U
