---
- name: Include variables.
  include_vars: "main.yml"

- name: Copy jdk to remote host {{ work_dir }}.
  copy: "src={{ oracle_jdk_version }} dest={{ work_dir }}"

- name: "mkdir {{ java_default_path }}"
  file: "path={{ java_default_path }} state=directory mode=0755"

- name: Unzip jdk.
  unarchive: "src={{ work_dir }}/{{ oracle_jdk_version }} dest={{ java_default_path }} owner=root group=root copy=no"

- name: Set JAVA_HOME.
  template:
    src: java_home.sh.j2
    dest: "/etc/profile.d/java_home.sh"
    mode: 0644

- name: Source /etc/profile.d/java_home.sh.
  shell: source /etc/profile.d/java_home.sh

- name: java version
  shell: java -version

- name: Remove files.
  file: "path={{ work_dir }}/{{ oracle_jdk_version }} state=absent"
