---

- name: Copy chrony config
  copy:
    src: etc/chrony.conf
    dest: /etc/chrony.conf
    mode: '0644'

- name: Set timezone to Asia/Shanghai
  timezone:
    name: Asia/Shanghai

- name: Set ntp true
  shell: |
    timedatectl set-ntp true
    timedatectl set-local-rtc 0

- name: Restart chronyd
  systemd:
    name: chronyd
    state: restarted
    enabled: yes

- name: Ensure ntp packages are removed
  package:
    name: ntp
    state: removed
